### ISSUE TITLE
边界场景：js文件取不到AST

### ISSUE THREAD

**Issue by alvarto** [stcjs/stc#1]
如果一个文件中只有

```
(function(){

})();
```

AST为null，将触发如下位置报错。

![3 pic](https://cloud.githubusercontent.com/assets/1797855/16299746/6ec29a68-396e-11e6-9d5b-647e03405d30.jpg)

stc.config.js

```
var stc = require('stc'),
  uglify = require('stc-uglify');

stc.config({
  workers: 1,
  cluster: false,
  cache: false,
  include: ['template/'],
  tpl: {
    engine: 'smarty',
    extname: ['tpl', 'html'],
    ld: '{%',
    rd: '%}'
  }
});

stc.workflow({
  JSCompress: { plugin: uglify, include: /\.js$/ },
});

stc.start();
```

**Comment by welefen** [comment]
因为 uglify 把这个内容压缩为空导致的

修复方式见： https://github.com/stcjs/stc-file/commit/1a952b24bb58aeb8f44554371fb4627b3880f22c
